version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: MTCG_Container
    environment:
      POSTGRES_USER: toukage
      POSTGRES_PASSWORD: mtcgserver
      POSTGRES_DB: MTCG_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
